"""agregar_rut_y_password_a_users

Revision ID: 7f3c4417fe36
Revises: 87f4c51bde56
Create Date: 2025-11-22 23:19:12.971082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3c4417fe36'
down_revision: Union[str, Sequence[str], None] = '87f4c51bde56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rut', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_rut'), 'users', ['rut'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rut'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'rut')
    # ### end Alembic commands ###
